steps:
 # Docker Build
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'asia-docker.pkg.dev/${PROJECT_ID}/giovanni-api/test', '.']
 # Docker Push
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia-docker.pkg.dev/${PROJECT_ID}/giovanni-api/test']

